name: wallpaper_manager_plus
description: >
  A Flutter plugin to set wallpapers on Android: home screen, lock screen, or both. Uses Kotlin coroutines for efficient handling and prevents ANR issues.
version: 1.0.2
homepage: https://sawin.com.np
repository: https://github.com/sawin0/wallpaper_manager_plus
issue_tracker: https://github.com/sawin0/wallpaper_manager_plus/issues
documentation: https://github.com/sawin0/wallpaper_manager_plus#readme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

topics:
  - wallpaper
  - flutter-plugin
  - android-wallpaper
  - home-screen
  - lock-screen

flutter:
  plugin:
    platforms:
      android:
        package: np.com.sawin.wallpaper_manager_plus
        pluginClass: WallpaperManagerPlus
